version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: django_postgres
    environment:
      POSTGRES_DB: django_site_kyrs
      POSTGRES_USER: anzherus
      POSTGRES_PASSWORD: 1029384756SetKvazar
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
