# Generated by Django 5.2.6 on 2025-09-17 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_trener'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='trener',
        ),
    ]
