# Generated by Django 5.2.6 on 2025-09-19 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_service_userservice'),
        ('main', '0004_trening_category_trening'),
    ]

    operations = [
    ]
