# Generated by Django 5.2.6 on 2025-09-19 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_merge_20250919_1721'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trening',
        ),
        migrations.DeleteModel(
            name='Trening_category',
        ),
    ]
