
# Generated by Django 5.2.6 on 2025-10-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_trening_delete_trening_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='capacity',
            field=models.PositiveIntegerField(default=10, verbose_name='Количество мест'),
        ),
    ]
