# Generated by Django 5.2.6 on 2025-09-19 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.CharField(default='🏆', max_length=50, verbose_name='Иконка')),
                ('achievement_type', models.CharField(choices=[('workout', 'Тренировки'), ('service', 'Услуги'), ('shopping', 'Покупки'), ('social', 'Социальные'), ('system', 'Системные')], max_length=20, verbose_name='Тип ачивки')),
                ('points_reward', models.IntegerField(default=10, verbose_name='Награда в очках')),
                ('requirement', models.IntegerField(default=1, verbose_name='Требование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Ачивка',
                'verbose_name_plural': 'Ачивки',
                'ordering': ['achievement_type', 'requirement'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='experience_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0, verbose_name='Прогресс')),
                ('is_unlocked', models.BooleanField(default=False, verbose_name='Разблокирована')),
                ('unlocked_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата получения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ачивка пользователя',
                'verbose_name_plural': 'Ачивки пользователей',
                'ordering': ['-unlocked_at', '-created_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
