# Generated by Django 5.2.6 on 2025-09-19 23:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_achievement_customuser_experience_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('icon', models.CharField(default='⭐', max_length=20, verbose_name='Иконка')),
                ('category_type', models.CharField(choices=[('fitness', '🏋️ Фитнес'), ('nutrition', '🥗 Питание'), ('health', '💊 Здоровье'), ('lifestyle', '🌿 Образ жизни'), ('personal', '🎯 Личные цели')], max_length=20, verbose_name='Тип категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Категория прогресса',
                'verbose_name_plural': 'Категории прогресса',
                'ordering': ['category_type', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='achievement',
            name='achievement_type',
            field=models.CharField(choices=[('workout', 'Тренировки'), ('service', 'Услуги'), ('shopping', 'Покупки'), ('social', 'Социальные'), ('system', 'Системные'), ('progress', 'Прогресс')], max_length=20, verbose_name='Тип ачивки'),
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название цели')),
                ('description', models.TextField(blank=True, verbose_name='Описание цели')),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Целевое значение')),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Текущее значение')),
                ('unit', models.CharField(default='раз', max_length=20, verbose_name='Единица измерения')),
                ('status', models.CharField(choices=[('not_started', 'Не начато'), ('in_progress', 'В процессе'), ('completed', 'Завершено'), ('failed', 'Не удалось')], default='not_started', max_length=20, verbose_name='Статус')),
                ('priority', models.IntegerField(choices=[(1, 'Низкий'), (2, 'Средний'), (3, 'Высокий')], default=1, verbose_name='Приоритет')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершено')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.progresscategory', verbose_name='Категория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Прогресс пользователя',
                'verbose_name_plural': 'Прогресс пользователей',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_added', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Добавленное значение')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='user.userprogress')),
            ],
            options={
                'verbose_name': 'Обновление прогресса',
                'verbose_name_plural': 'Обновления прогресса',
                'ordering': ['-created_at'],
            },
        ),
    ]
